//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STOBWeb.Three60AuthorizationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Group", Namespace="http://schemas.datacontract.org/2004/07/Wsfg.Three60.Auth.Model")]
    [System.SerializableAttribute()]
    public partial class Group : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private STOBWeb.Three60AuthorizationService.GroupType GroupTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ManagingAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cn {
            get {
                return this.CnField;
            }
            set {
                if ((object.ReferenceEquals(this.CnField, value) != true)) {
                    this.CnField = value;
                    this.RaisePropertyChanged("Cn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public STOBWeb.Three60AuthorizationService.GroupType GroupType {
            get {
                return this.GroupTypeField;
            }
            set {
                if ((this.GroupTypeField.Equals(value) != true)) {
                    this.GroupTypeField = value;
                    this.RaisePropertyChanged("GroupType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ManagingAccount {
            get {
                return this.ManagingAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.ManagingAccountField, value) != true)) {
                    this.ManagingAccountField = value;
                    this.RaisePropertyChanged("ManagingAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Owner {
            get {
                return this.OwnerField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerField, value) != true)) {
                    this.OwnerField = value;
                    this.RaisePropertyChanged("Owner");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GroupType", Namespace="http://schemas.datacontract.org/2004/07/Wsfg.Three60.Auth.Model")]
    public enum GroupType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Affiliate = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Security = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Agency = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Wsfg.Three60.Auth.Model")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AcfIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeptNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExemptStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FloorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailStationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ManagerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ManagerLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] MemberOfGroupListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrgCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PositionNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreferredNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegTempField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReportsToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cnField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AcfId {
            get {
                return this.AcfIdField;
            }
            set {
                if ((object.ReferenceEquals(this.AcfIdField, value) != true)) {
                    this.AcfIdField = value;
                    this.RaisePropertyChanged("AcfId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Building {
            get {
                return this.BuildingField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildingField, value) != true)) {
                    this.BuildingField = value;
                    this.RaisePropertyChanged("Building");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyCode {
            get {
                return this.CompanyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyCodeField, value) != true)) {
                    this.CompanyCodeField = value;
                    this.RaisePropertyChanged("CompanyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentID {
            get {
                return this.DepartmentIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentIDField, value) != true)) {
                    this.DepartmentIDField = value;
                    this.RaisePropertyChanged("DepartmentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeptName {
            get {
                return this.DeptNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DeptNameField, value) != true)) {
                    this.DeptNameField = value;
                    this.RaisePropertyChanged("DeptName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMail {
            get {
                return this.EMailField;
            }
            set {
                if ((object.ReferenceEquals(this.EMailField, value) != true)) {
                    this.EMailField = value;
                    this.RaisePropertyChanged("EMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeIDField, value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeType {
            get {
                return this.EmployeeTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeTypeField, value) != true)) {
                    this.EmployeeTypeField = value;
                    this.RaisePropertyChanged("EmployeeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExemptStatus {
            get {
                return this.ExemptStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.ExemptStatusField, value) != true)) {
                    this.ExemptStatusField = value;
                    this.RaisePropertyChanged("ExemptStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Floor {
            get {
                return this.FloorField;
            }
            set {
                if ((object.ReferenceEquals(this.FloorField, value) != true)) {
                    this.FloorField = value;
                    this.RaisePropertyChanged("Floor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobNumber {
            get {
                return this.JobNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.JobNumberField, value) != true)) {
                    this.JobNumberField = value;
                    this.RaisePropertyChanged("JobNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailStation {
            get {
                return this.MailStationField;
            }
            set {
                if ((object.ReferenceEquals(this.MailStationField, value) != true)) {
                    this.MailStationField = value;
                    this.RaisePropertyChanged("MailStation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Manager {
            get {
                return this.ManagerField;
            }
            set {
                if ((object.ReferenceEquals(this.ManagerField, value) != true)) {
                    this.ManagerField = value;
                    this.RaisePropertyChanged("Manager");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ManagerLevel {
            get {
                return this.ManagerLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.ManagerLevelField, value) != true)) {
                    this.ManagerLevelField = value;
                    this.RaisePropertyChanged("ManagerLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] MemberOfGroupList {
            get {
                return this.MemberOfGroupListField;
            }
            set {
                if ((object.ReferenceEquals(this.MemberOfGroupListField, value) != true)) {
                    this.MemberOfGroupListField = value;
                    this.RaisePropertyChanged("MemberOfGroupList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OU {
            get {
                return this.OUField;
            }
            set {
                if ((object.ReferenceEquals(this.OUField, value) != true)) {
                    this.OUField = value;
                    this.RaisePropertyChanged("OU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrgCode {
            get {
                return this.OrgCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.OrgCodeField, value) != true)) {
                    this.OrgCodeField = value;
                    this.RaisePropertyChanged("OrgCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayGroup {
            get {
                return this.PayGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.PayGroupField, value) != true)) {
                    this.PayGroupField = value;
                    this.RaisePropertyChanged("PayGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PositionNumber {
            get {
                return this.PositionNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PositionNumberField, value) != true)) {
                    this.PositionNumberField = value;
                    this.RaisePropertyChanged("PositionNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreferredName {
            get {
                return this.PreferredNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PreferredNameField, value) != true)) {
                    this.PreferredNameField = value;
                    this.RaisePropertyChanged("PreferredName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegTemp {
            get {
                return this.RegTempField;
            }
            set {
                if ((object.ReferenceEquals(this.RegTempField, value) != true)) {
                    this.RegTempField = value;
                    this.RaisePropertyChanged("RegTemp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportsTo {
            get {
                return this.ReportsToField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportsToField, value) != true)) {
                    this.ReportsToField = value;
                    this.RaisePropertyChanged("ReportsTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((object.ReferenceEquals(this.StartDateField, value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Uid {
            get {
                return this.UidField;
            }
            set {
                if ((object.ReferenceEquals(this.UidField, value) != true)) {
                    this.UidField = value;
                    this.RaisePropertyChanged("Uid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cn {
            get {
                return this.cnField;
            }
            set {
                if ((object.ReferenceEquals(this.cnField, value) != true)) {
                    this.cnField = value;
                    this.RaisePropertyChanged("cn");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Wsfg.Three60.Auth.Services/", ConfigurationName="Three60AuthorizationService.AuthorizationServiceSoap")]
    public interface AuthorizationServiceSoap {
        
        // CODEGEN: Generating message contract since the wrapper name (AuthorizationRequest) of message AuthorizationRequest does not match the default value (IsInGroup)
        [System.ServiceModel.OperationContractAttribute(Action="http://Wsfg.Three60.Auth.Services/IsInGroup", ReplyAction="http://Wsfg.Three60.Auth.Services/AuthorizationServiceSoap/IsInGroupResponse")]
        STOBWeb.Three60AuthorizationService.AuthorizationResponse IsInGroup(STOBWeb.Three60AuthorizationService.AuthorizationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Wsfg.Three60.Auth.Services/IsInGroup", ReplyAction="http://Wsfg.Three60.Auth.Services/AuthorizationServiceSoap/IsInGroupResponse")]
        System.Threading.Tasks.Task<STOBWeb.Three60AuthorizationService.AuthorizationResponse> IsInGroupAsync(STOBWeb.Three60AuthorizationService.AuthorizationRequest request);
        
        // CODEGEN: Generating message contract since the operation GetAllGroups is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://Wsfg.Three60.Auth.Services/GetAllGroups", ReplyAction="http://Wsfg.Three60.Auth.Services/AuthorizationServiceSoap/GetAllGroupsResponse")]
        STOBWeb.Three60AuthorizationService.GroupResponse GetAllGroups(STOBWeb.Three60AuthorizationService.GetAllGroupsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Wsfg.Three60.Auth.Services/GetAllGroups", ReplyAction="http://Wsfg.Three60.Auth.Services/AuthorizationServiceSoap/GetAllGroupsResponse")]
        System.Threading.Tasks.Task<STOBWeb.Three60AuthorizationService.GroupResponse> GetAllGroupsAsync(STOBWeb.Three60AuthorizationService.GetAllGroupsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (GroupRequest) of message GroupRequest does not match the default value (GetGroupsForUser)
        [System.ServiceModel.OperationContractAttribute(Action="http://Wsfg.Three60.Auth.Services/GetGroupsForUser", ReplyAction="http://Wsfg.Three60.Auth.Services/AuthorizationServiceSoap/GetGroupsForUserRespon" +
            "se")]
        STOBWeb.Three60AuthorizationService.GroupResponse GetGroupsForUser(STOBWeb.Three60AuthorizationService.GroupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Wsfg.Three60.Auth.Services/GetGroupsForUser", ReplyAction="http://Wsfg.Three60.Auth.Services/AuthorizationServiceSoap/GetGroupsForUserRespon" +
            "se")]
        System.Threading.Tasks.Task<STOBWeb.Three60AuthorizationService.GroupResponse> GetGroupsForUserAsync(STOBWeb.Three60AuthorizationService.GroupRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (GroupUserRequest) of message GroupUserRequest does not match the default value (GetUsersInGroup)
        [System.ServiceModel.OperationContractAttribute(Action="http://Wsfg.Three60.Auth.Services/GetUsersInGroup", ReplyAction="http://Wsfg.Three60.Auth.Services/AuthorizationServiceSoap/GetUsersInGroupRespons" +
            "e")]
        STOBWeb.Three60AuthorizationService.UserResponse GetUsersInGroup(STOBWeb.Three60AuthorizationService.GroupUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Wsfg.Three60.Auth.Services/GetUsersInGroup", ReplyAction="http://Wsfg.Three60.Auth.Services/AuthorizationServiceSoap/GetUsersInGroupRespons" +
            "e")]
        System.Threading.Tasks.Task<STOBWeb.Three60AuthorizationService.UserResponse> GetUsersInGroupAsync(STOBWeb.Three60AuthorizationService.GroupUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthorizationRequest", WrapperNamespace="http://Wsfg.Three60.Auth.Services/", IsWrapped=true)]
    public partial class AuthorizationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Wsfg.Three60.Auth.Services/", Order=0)]
        public string AccountName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Wsfg.Three60.Auth.Services/", Order=1)]
        public string Group;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Wsfg.Three60.Auth.Services/", Order=2)]
        public bool SearchSubGroups;
        
        public AuthorizationRequest() {
        }
        
        public AuthorizationRequest(string AccountName, string Group, bool SearchSubGroups) {
            this.AccountName = AccountName;
            this.Group = Group;
            this.SearchSubGroups = SearchSubGroups;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthorizationResponse", WrapperNamespace="http://Wsfg.Three60.Auth.Services/", IsWrapped=true)]
    public partial class AuthorizationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Wsfg.Three60.Auth.Services/", Order=0)]
        public bool InGroup;
        
        public AuthorizationResponse() {
        }
        
        public AuthorizationResponse(bool InGroup) {
            this.InGroup = InGroup;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllGroupsRequest {
        
        public GetAllGroupsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GroupResponse", WrapperNamespace="http://Wsfg.Three60.Auth.Services/", IsWrapped=true)]
    public partial class GroupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Wsfg.Three60.Auth.Services/", Order=0)]
        public STOBWeb.Three60AuthorizationService.Group[] Group;
        
        public GroupResponse() {
        }
        
        public GroupResponse(STOBWeb.Three60AuthorizationService.Group[] Group) {
            this.Group = Group;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GroupRequest", WrapperNamespace="http://Wsfg.Three60.Auth.Services/", IsWrapped=true)]
    public partial class GroupRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Wsfg.Three60.Auth.Services/", Order=0)]
        public string AccountName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Wsfg.Three60.Auth.Services/", Order=1)]
        public bool SearchSubGroups;
        
        public GroupRequest() {
        }
        
        public GroupRequest(string AccountName, bool SearchSubGroups) {
            this.AccountName = AccountName;
            this.SearchSubGroups = SearchSubGroups;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GroupUserRequest", WrapperNamespace="http://Wsfg.Three60.Auth.Services/", IsWrapped=true)]
    public partial class GroupUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Wsfg.Three60.Auth.Services/", Order=0)]
        public string GroupName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Wsfg.Three60.Auth.Services/", Order=1)]
        public bool SearchSubGroups;
        
        public GroupUserRequest() {
        }
        
        public GroupUserRequest(string GroupName, bool SearchSubGroups) {
            this.GroupName = GroupName;
            this.SearchSubGroups = SearchSubGroups;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserResponse", WrapperNamespace="http://Wsfg.Three60.Auth.Services/", IsWrapped=true)]
    public partial class UserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Wsfg.Three60.Auth.Services/", Order=0)]
        public STOBWeb.Three60AuthorizationService.User[] Users;
        
        public UserResponse() {
        }
        
        public UserResponse(STOBWeb.Three60AuthorizationService.User[] Users) {
            this.Users = Users;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AuthorizationServiceSoapChannel : STOBWeb.Three60AuthorizationService.AuthorizationServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthorizationServiceSoapClient : System.ServiceModel.ClientBase<STOBWeb.Three60AuthorizationService.AuthorizationServiceSoap>, STOBWeb.Three60AuthorizationService.AuthorizationServiceSoap {
        
        public AuthorizationServiceSoapClient() {
        }
        
        public AuthorizationServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthorizationServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthorizationServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthorizationServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        STOBWeb.Three60AuthorizationService.AuthorizationResponse STOBWeb.Three60AuthorizationService.AuthorizationServiceSoap.IsInGroup(STOBWeb.Three60AuthorizationService.AuthorizationRequest request) {
            return base.Channel.IsInGroup(request);
        }
        
        public bool IsInGroup(string AccountName, string Group, bool SearchSubGroups) {
            STOBWeb.Three60AuthorizationService.AuthorizationRequest inValue = new STOBWeb.Three60AuthorizationService.AuthorizationRequest();
            inValue.AccountName = AccountName;
            inValue.Group = Group;
            inValue.SearchSubGroups = SearchSubGroups;
            STOBWeb.Three60AuthorizationService.AuthorizationResponse retVal = ((STOBWeb.Three60AuthorizationService.AuthorizationServiceSoap)(this)).IsInGroup(inValue);
            return retVal.InGroup;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<STOBWeb.Three60AuthorizationService.AuthorizationResponse> STOBWeb.Three60AuthorizationService.AuthorizationServiceSoap.IsInGroupAsync(STOBWeb.Three60AuthorizationService.AuthorizationRequest request) {
            return base.Channel.IsInGroupAsync(request);
        }
        
        public System.Threading.Tasks.Task<STOBWeb.Three60AuthorizationService.AuthorizationResponse> IsInGroupAsync(string AccountName, string Group, bool SearchSubGroups) {
            STOBWeb.Three60AuthorizationService.AuthorizationRequest inValue = new STOBWeb.Three60AuthorizationService.AuthorizationRequest();
            inValue.AccountName = AccountName;
            inValue.Group = Group;
            inValue.SearchSubGroups = SearchSubGroups;
            return ((STOBWeb.Three60AuthorizationService.AuthorizationServiceSoap)(this)).IsInGroupAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        STOBWeb.Three60AuthorizationService.GroupResponse STOBWeb.Three60AuthorizationService.AuthorizationServiceSoap.GetAllGroups(STOBWeb.Three60AuthorizationService.GetAllGroupsRequest request) {
            return base.Channel.GetAllGroups(request);
        }
        
        public STOBWeb.Three60AuthorizationService.Group[] GetAllGroups() {
            STOBWeb.Three60AuthorizationService.GetAllGroupsRequest inValue = new STOBWeb.Three60AuthorizationService.GetAllGroupsRequest();
            STOBWeb.Three60AuthorizationService.GroupResponse retVal = ((STOBWeb.Three60AuthorizationService.AuthorizationServiceSoap)(this)).GetAllGroups(inValue);
            return retVal.Group;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<STOBWeb.Three60AuthorizationService.GroupResponse> STOBWeb.Three60AuthorizationService.AuthorizationServiceSoap.GetAllGroupsAsync(STOBWeb.Three60AuthorizationService.GetAllGroupsRequest request) {
            return base.Channel.GetAllGroupsAsync(request);
        }
        
        public System.Threading.Tasks.Task<STOBWeb.Three60AuthorizationService.GroupResponse> GetAllGroupsAsync() {
            STOBWeb.Three60AuthorizationService.GetAllGroupsRequest inValue = new STOBWeb.Three60AuthorizationService.GetAllGroupsRequest();
            return ((STOBWeb.Three60AuthorizationService.AuthorizationServiceSoap)(this)).GetAllGroupsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        STOBWeb.Three60AuthorizationService.GroupResponse STOBWeb.Three60AuthorizationService.AuthorizationServiceSoap.GetGroupsForUser(STOBWeb.Three60AuthorizationService.GroupRequest request) {
            return base.Channel.GetGroupsForUser(request);
        }
        
        public STOBWeb.Three60AuthorizationService.Group[] GetGroupsForUser(string AccountName, bool SearchSubGroups) {
            STOBWeb.Three60AuthorizationService.GroupRequest inValue = new STOBWeb.Three60AuthorizationService.GroupRequest();
            inValue.AccountName = AccountName;
            inValue.SearchSubGroups = SearchSubGroups;
            STOBWeb.Three60AuthorizationService.GroupResponse retVal = ((STOBWeb.Three60AuthorizationService.AuthorizationServiceSoap)(this)).GetGroupsForUser(inValue);
            return retVal.Group;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<STOBWeb.Three60AuthorizationService.GroupResponse> STOBWeb.Three60AuthorizationService.AuthorizationServiceSoap.GetGroupsForUserAsync(STOBWeb.Three60AuthorizationService.GroupRequest request) {
            return base.Channel.GetGroupsForUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<STOBWeb.Three60AuthorizationService.GroupResponse> GetGroupsForUserAsync(string AccountName, bool SearchSubGroups) {
            STOBWeb.Three60AuthorizationService.GroupRequest inValue = new STOBWeb.Three60AuthorizationService.GroupRequest();
            inValue.AccountName = AccountName;
            inValue.SearchSubGroups = SearchSubGroups;
            return ((STOBWeb.Three60AuthorizationService.AuthorizationServiceSoap)(this)).GetGroupsForUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        STOBWeb.Three60AuthorizationService.UserResponse STOBWeb.Three60AuthorizationService.AuthorizationServiceSoap.GetUsersInGroup(STOBWeb.Three60AuthorizationService.GroupUserRequest request) {
            return base.Channel.GetUsersInGroup(request);
        }
        
        public STOBWeb.Three60AuthorizationService.User[] GetUsersInGroup(string GroupName, bool SearchSubGroups) {
            STOBWeb.Three60AuthorizationService.GroupUserRequest inValue = new STOBWeb.Three60AuthorizationService.GroupUserRequest();
            inValue.GroupName = GroupName;
            inValue.SearchSubGroups = SearchSubGroups;
            STOBWeb.Three60AuthorizationService.UserResponse retVal = ((STOBWeb.Three60AuthorizationService.AuthorizationServiceSoap)(this)).GetUsersInGroup(inValue);
            return retVal.Users;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<STOBWeb.Three60AuthorizationService.UserResponse> STOBWeb.Three60AuthorizationService.AuthorizationServiceSoap.GetUsersInGroupAsync(STOBWeb.Three60AuthorizationService.GroupUserRequest request) {
            return base.Channel.GetUsersInGroupAsync(request);
        }
        
        public System.Threading.Tasks.Task<STOBWeb.Three60AuthorizationService.UserResponse> GetUsersInGroupAsync(string GroupName, bool SearchSubGroups) {
            STOBWeb.Three60AuthorizationService.GroupUserRequest inValue = new STOBWeb.Three60AuthorizationService.GroupUserRequest();
            inValue.GroupName = GroupName;
            inValue.SearchSubGroups = SearchSubGroups;
            return ((STOBWeb.Three60AuthorizationService.AuthorizationServiceSoap)(this)).GetUsersInGroupAsync(inValue);
        }
    }
}
